version = 0.1
[default.deploy.parameters]
stack_name = "check-uranai-text-lambda-stack"
resolve_s3 = true
s3_prefix = "check-uranai-text-lambda-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
