AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main.handler
      Runtime: python3.9
      Events:
        CompareToppage:
          Type: Api
          Properties:
            Path: /api/compare/toppage
            Method: post
        CompareInputpage:
          Type: Api
          Properties:
            Path: /api/compare/inputpage
            Method: post